"""Markdown renderer — also the reference implementation: what you can read
here is exactly what every other format contains."""


def _marks(item: dict) -> str:
    marks = "".join(f"[{n}]" for n in item.get("citations", []))
    if item.get("unreviewed"):
        marks += " *"
    return f" {marks}" if marks else ""


def render_md(spec: dict) -> bytes:
    lines: list[str] = [
        f"# {spec['title']}",
        "",
        f"_Generated {spec['generated_at'][:10]} · model {spec['review_coverage']} "
        "analyst-reviewed · every figure derives from the ROI assumption sheets_",
        "",
    ]
    for section in spec["sections"]:
        lines += [f"## {section['heading']}", ""]
        kind = section["kind"]
        if kind == "overview":
            lines += [section["body"], ""]
            for stat in section["stats"]:
                lines.append(f"- **{stat['label']}**: {stat['value']}")
            lines.append("")
        elif kind == "findings":
            for item in section["items"]:
                taxonomy = f" _({item['taxonomy']})_" if item.get("taxonomy") else ""
                lines.append(f"- {item['text']}{taxonomy}{_marks(item)}")
            lines.append("")
        elif kind == "opportunities":
            lines.append(
                "| Opportunity | Type | Impact | Complexity | Risk | Net annual | Payback |"
            )
            lines.append("|---|---|---|---|---|---|---|")
            for row in section["rows"]:
                net = (
                    f"${row['net_annual_savings']:,.0f}"
                    if row.get("net_annual_savings") is not None
                    else "—"
                )
                payback = (
                    f"{row['payback_months']} mo"
                    if row.get("payback_months")
                    else "—"
                )
                lines.append(
                    f"| {row['title']}{_marks(row)} | {row['taxonomy']} "
                    f"| {row['impact']} | {row['complexity']} | {row['risk']} "
                    f"| {net} | {payback} |"
                )
            lines.append("")
        elif kind == "roadmap":
            for horizon, label in (
                ("30", "First 30 days"), ("90", "90 days"),
                ("180", "6 months"), ("365", "12 months"),
            ):
                items = section["horizons"].get(horizon, [])
                lines.append(f"**{label}**")
                lines += [
                    f"- {i['title']}{' ⚡' if i.get('quick_win') else ''}"
                    for i in items
                ] or ["- —"]
                lines.append("")
        elif kind == "process":
            lines.append(f"_Process{_marks(section)}_")
            lines.append("")
            lines.append("| # | Step | Type | Performer |")
            lines.append("|---|---|---|---|")
            for step in section["steps"]:
                lines.append(
                    f"| {step['order']} | {step['name']}{_marks(step)} "
                    f"| {step['step_type']} | {step['performer']} |"
                )
            lines.append("")
            if section["pain_points"]:
                lines.append("**Pain points**")
                for pain in section["pain_points"]:
                    taxonomy = f" _({pain['taxonomy']})_" if pain.get("taxonomy") else ""
                    lines.append(f"- {pain['text']}{taxonomy}{_marks(pain)}")
                lines.append("")
        elif kind == "table":
            lines.append("| " + " | ".join(section["columns"]) + " |")
            lines.append("|" + "---|" * len(section["columns"]))
            for row in section["rows"]:
                lines.append("| " + " | ".join(str(c) for c in row) + " |")
            lines.append("")

    if spec["citations"]:
        lines += ["## Sources", ""]
        for citation in spec["citations"]:
            quote = f' — "{citation["quote"]}"' if citation.get("quote") else ""
            lines.append(f"{citation['n']}. **{citation['filename']}**{quote}")
        lines.append("")
    lines.append("_* item generated by AI and not yet analyst-reviewed_")
    return "\n".join(lines).encode()
