/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Login
         * @description Password-less login for local development.
         *
         *     Registered only when auth_mode=dev; config validation refuses that mode
         *     in production (app.config).
         */
        post: operations["dev_login_v1_auth_dev_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/workos/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workos Callback */
        get: operations["workos_callback_v1_auth_workos_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/workos/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workos Login */
        get: operations["workos_login_v1_auth_workos_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_v1_orgs__org_id__documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/documents/{document_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Document Upload
         * @description Step 2: confirm the blob landed, then kick off the ingestion pipeline.
         */
        post: operations["complete_document_upload_v1_orgs__org_id__documents__document_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/entities/{entity_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Entity */
        post: operations["review_entity_v1_orgs__org_id__entities__entity_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/pipeline-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_orgs__org_id__pipeline_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/pipeline-runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description SSE stream of run snapshots until the run reaches a terminal state.
         *
         *     M0 implementation polls the database once per second — honest, simple,
         *     and replaceable by LISTEN/NOTIFY without changing the wire contract.
         */
        get: operations["run_events_v1_orgs__org_id__pipeline_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/processes/{process_id}/bpmn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process Bpmn */
        get: operations["process_bpmn_v1_orgs__org_id__processes__process_id__bpmn_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/processes/{process_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process Graph */
        get: operations["process_graph_v1_orgs__org_id__processes__process_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_v1_orgs__org_id__projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_v1_orgs__org_id__projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_v1_orgs__org_id__projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/projects/{project_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_v1_orgs__org_id__projects__project_id__documents_get"];
        put?: never;
        /**
         * Create Document Upload
         * @description Step 1 of upload: register the document, hand back a presigned PUT URL.
         *
         *     The browser uploads directly to object storage — document bytes never
         *     stream through the API process.
         */
        post: operations["create_document_upload_v1_orgs__org_id__projects__project_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/projects/{project_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entities */
        get: operations["list_entities_v1_orgs__org_id__projects__project_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/projects/{project_id}/knowledge/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Extraction */
        post: operations["start_extraction_v1_orgs__org_id__projects__project_id__knowledge_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/projects/{project_id}/knowledge/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Knowledge Summary */
        get: operations["knowledge_summary_v1_orgs__org_id__projects__project_id__knowledge_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/projects/{project_id}/review-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Review Items */
        get: operations["list_review_items_v1_orgs__org_id__projects__project_id__review_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/projects/{project_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Project */
        post: operations["search_project_v1_orgs__org_id__projects__project_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org_id}/review-items/{item_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Review Item */
        post: operations["resolve_review_item_v1_orgs__org_id__review_items__item_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low";
        /** DevLoginRequest */
        DevLoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
        };
        /** DocumentCompleteOut */
        DocumentCompleteOut: {
            document: components["schemas"]["DocumentOut"];
            /**
             * Pipeline Run Id
             * Format: uuid
             */
            pipeline_run_id: string;
        };
        /** DocumentCreate */
        DocumentCreate: {
            /** Filename */
            filename: string;
            /** Mime */
            mime: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** DocumentDetailOut */
        DocumentDetailOut: {
            /** Doc Class */
            doc_class: string | null;
            document: components["schemas"]["DocumentOut"];
            /** Element Count */
            element_count: number;
            /** Elements */
            elements: components["schemas"]["ElementOut"][];
            /** Pii Summary */
            pii_summary: {
                [key: string]: unknown;
            } | null;
        };
        /** DocumentListItem */
        DocumentListItem: {
            /** Content Hash */
            content_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Doc Class */
            doc_class?: string | null;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latest Run Id */
            latest_run_id?: string | null;
            latest_run_status?: components["schemas"]["RunStatus"] | null;
            /** Mime */
            mime: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Size Bytes */
            size_bytes: number | null;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Content Hash */
            content_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mime */
            mime: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Size Bytes */
            size_bytes: number | null;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "pending_upload" | "uploaded" | "processing" | "ready" | "failed";
        /** DocumentUploadOut */
        DocumentUploadOut: {
            document: components["schemas"]["DocumentOut"];
            /** Upload Url */
            upload_url: string;
        };
        /** ElementOut */
        ElementOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Order Key */
            order_key: number;
            /** Page */
            page: number | null;
            /**
             * Pii Types
             * @default []
             */
            pii_types: string[];
            /** Section Path */
            section_path: unknown[];
            /** Table Json */
            table_json: {
                [key: string]: unknown;
            } | null;
            /** Text */
            text: string;
        };
        /** EntityOut */
        EntityOut: {
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
            confidence: components["schemas"]["Confidence"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["EvidenceOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Novel */
            novel: boolean;
            review_state: components["schemas"]["ReviewState"];
            /** Type */
            type: string;
            /** Version */
            version: number;
        };
        /** EntityReviewIn */
        EntityReviewIn: {
            /** Action */
            action: string;
            /** Edits */
            edits?: {
                [key: string]: unknown;
            } | null;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Element Id
             * Format: uuid
             */
            element_id: string;
            /** Filename */
            filename?: string | null;
            /** Quote */
            quote: string | null;
        };
        /** ExtractOut */
        ExtractOut: {
            /**
             * Pipeline Run Id
             * Format: uuid
             */
            pipeline_run_id: string;
        };
        /** GraphEdgeOut */
        GraphEdgeOut: {
            /**
             * From Id
             * Format: uuid
             */
            from_id: string;
            /**
             * To Id
             * Format: uuid
             */
            to_id: string;
        };
        /** GraphNodeOut */
        GraphNodeOut: {
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["EvidenceOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lane */
            lane: string;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /**
             * Pain Points
             * @default []
             */
            pain_points: {
                [key: string]: unknown;
            }[];
            review_state: components["schemas"]["ReviewState"];
            /** Step Type */
            step_type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KnowledgeSummaryOut */
        KnowledgeSummaryOut: {
            /** By Review State */
            by_review_state: {
                [key: string]: number;
            };
            /** Entities By Type */
            entities_by_type: {
                [key: string]: number;
            };
            /** Open Review Items */
            open_review_items: number;
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Orgs */
            orgs: components["schemas"]["OrgSummary"][];
        };
        /** OrgSummary */
        OrgSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Slug */
            slug: string;
        };
        /** ProcessGraphOut */
        ProcessGraphOut: {
            /** Edges */
            edges: components["schemas"]["GraphEdgeOut"][];
            /** Lanes */
            lanes: string[];
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            process: components["schemas"]["EntityOut"];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /**
             * Industry Pack
             * @default insurance-claims
             */
            industry_pack: string;
            /** Name */
            name: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Industry Pack */
            industry_pack: string;
            /** Name */
            name: string;
            status: components["schemas"]["ProjectStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "archived";
        /** ResolveIn */
        ResolveIn: {
            /** Action */
            action: string;
        };
        /** ReviewItemOut */
        ReviewItemOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Question */
            question: string;
            /** Status */
            status: string;
            subject?: components["schemas"]["EntityOut"] | null;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Subject Type */
            subject_type: string;
        };
        /**
         * ReviewItemStatus
         * @enum {string}
         */
        ReviewItemStatus: "open" | "resolved" | "dismissed";
        /**
         * ReviewState
         * @enum {string}
         */
        ReviewState: "ai_generated" | "confirmed" | "edited" | "rejected";
        /** RunOut */
        RunOut: {
            /** Context */
            context: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["RunStatus"];
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed";
        /** SearchHit */
        SearchHit: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Doc Class */
            doc_class: string | null;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Element Ids */
            element_ids: string[];
            /** Filename */
            filename: string;
            /** Pages */
            pages: unknown[];
            /** Score */
            score: number;
            /** Section Path */
            section_path: unknown[];
            /** Text */
            text: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 8
             */
            top_k: number;
        };
        /** StepOut */
        StepOut: {
            /** Attempt */
            attempt: number;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Name */
            name: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["StepStatus"];
        };
        /**
         * StepStatus
         * @enum {string}
         */
        StepStatus: "running" | "succeeded" | "failed" | "skipped";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dev_login_v1_auth_dev_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workos_callback_v1_auth_workos_callback_get: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workos_login_v1_auth_workos_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_document_v1_orgs__org_id__documents__document_id__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                document_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_document_upload_v1_orgs__org_id__documents__document_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentCompleteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_entity_v1_orgs__org_id__entities__entity_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_orgs__org_id__pipeline_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_v1_orgs__org_id__pipeline_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_bpmn_v1_orgs__org_id__processes__process_id__bpmn_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_graph_v1_orgs__org_id__processes__process_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessGraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_v1_orgs__org_id__projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_v1_orgs__org_id__projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_v1_orgs__org_id__projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_orgs__org_id__projects__project_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_upload_v1_orgs__org_id__projects__project_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_v1_orgs__org_id__projects__project_id__entities_get: {
        parameters: {
            query?: {
                type?: string | null;
                review_state?: components["schemas"]["ReviewState"] | null;
                include_rejected?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_extraction_v1_orgs__org_id__projects__project_id__knowledge_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    knowledge_summary_v1_orgs__org_id__projects__project_id__knowledge_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_review_items_v1_orgs__org_id__projects__project_id__review_items_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReviewItemStatus"];
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_project_v1_orgs__org_id__projects__project_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_review_item_v1_orgs__org_id__review_items__item_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
                org_id: string;
            };
            cookie?: {
                atc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
