"""Opportunities, ROI models, roadmap items (docs/06 M3).

The quantitative discipline (docs/01 §2.5): the AI proposes assumptions —
each cited to evidence or flagged as an estimate — the analyst edits them,
and every figure is computed in code from those assumptions. ROI rows are
versioned so a deck can always say which assumption sheet produced it.
"""

import enum
import uuid

from sqlalchemy import Enum, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base, TimestampMixin, uuid7_pk
from app.modules.knowledge.models import ReviewState


class OpportunityTaxonomy(enum.StrEnum):
    system_integration = "system_integration"
    rpa = "rpa"
    workflow_automation = "workflow_automation"
    document_ai = "document_ai"
    decision_engine = "decision_engine"
    generative_ai = "generative_ai"
    knowledge_search = "knowledge_search"
    process_redesign = "process_redesign"
    elimination = "elimination"


class Opportunity(Base, TimestampMixin):
    __tablename__ = "opportunities"

    id: Mapped[uuid.UUID] = uuid7_pk()
    org_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("orgs.id", ondelete="CASCADE"), index=True
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), index=True
    )
    process_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("entities.id", ondelete="SET NULL")
    )
    taxonomy_type: Mapped[OpportunityTaxonomy] = mapped_column(
        Enum(OpportunityTaxonomy, name="opportunity_taxonomy")
    )
    title: Mapped[str] = mapped_column(String(300))
    description: Mapped[str] = mapped_column(Text)
    # 1–5 scales; rubric_version pins which rules produced them.
    impact_score: Mapped[int] = mapped_column(Integer)
    complexity_score: Mapped[int] = mapped_column(Integer)
    risk_score: Mapped[int] = mapped_column(Integer)
    rationale: Mapped[str] = mapped_column(Text)
    rubric_version: Mapped[str] = mapped_column(String(20))
    review_state: Mapped[ReviewState] = mapped_column(
        Enum(ReviewState, name="review_state", create_type=False),
        default=ReviewState.ai_generated,
    )
    # pain_point_ids and any generator context
    attrs: Mapped[dict] = mapped_column(JSONB, default=dict)
    source: Mapped[str] = mapped_column(String(50), default="pipeline")


class RoiModel(Base, TimestampMixin):
    __tablename__ = "roi_models"

    id: Mapped[uuid.UUID] = uuid7_pk()
    org_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("orgs.id", ondelete="CASCADE"), index=True
    )
    opportunity_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("opportunities.id", ondelete="CASCADE"),
        index=True, unique=True,
    )
    version: Mapped[int] = mapped_column(Integer, default=1)
    # [{key, label, value, unit, source: 'estimate'|'analyst'|evidence_id}]
    assumptions: Mapped[list] = mapped_column(JSONB, default=list)
    # Regenerated by code from assumptions — never hand-written (docs/04).
    computed: Mapped[dict] = mapped_column(JSONB, default=dict)


class RoadmapHorizon(enum.StrEnum):
    days_30 = "30"
    days_90 = "90"
    days_180 = "180"
    days_365 = "365"


class RoadmapItem(Base, TimestampMixin):
    """Derived sequencing over scored opportunities. Regenerating the
    roadmap replaces these rows; analyst judgments live on opportunities."""

    __tablename__ = "roadmap_items"

    id: Mapped[uuid.UUID] = uuid7_pk()
    org_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("orgs.id", ondelete="CASCADE"), index=True
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), index=True
    )
    opportunity_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("opportunities.id", ondelete="CASCADE")
    )
    horizon: Mapped[RoadmapHorizon] = mapped_column(
        Enum(RoadmapHorizon, name="roadmap_horizon")
    )
    position: Mapped[int] = mapped_column(Integer, default=0)
    quick_win: Mapped[bool] = mapped_column(default=False)
    rationale: Mapped[str] = mapped_column(Text)
    depends_on: Mapped[list] = mapped_column(JSONB, default=list)  # opportunity ids
