"""m4 deliverables

Revision ID: 8d97db86db8a
Revises: cbd4e3fd608e
Create Date: 2026-07-04 11:12:44.823663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8d97db86db8a'
down_revision = 'cbd4e3fd608e'
branch_labels = None
depends_on = None

TENANT_TABLES = ["deliverables", "deliverable_versions"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('executive_summary', 'current_state_assessment', 'opportunity_register', 'roadmap_deck', name='deliverable_type'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverables_org_id'), 'deliverables', ['org_id'], unique=False)
    op.create_index(op.f('ix_deliverables_project_id'), 'deliverables', ['project_id'], unique=False)
    op.create_table('deliverable_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('deliverable_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generator_version', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deliverable_id', 'version', name='uq_deliverable_version')
    )
    op.create_index(op.f('ix_deliverable_versions_deliverable_id'), 'deliverable_versions', ['deliverable_id'], unique=False)
    op.create_index(op.f('ix_deliverable_versions_org_id'), 'deliverable_versions', ['org_id'], unique=False)
    # ### end Alembic commands ###

    # Row-Level Security, same shape as prior migrations (docs/05 §2).
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
            WITH CHECK (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
            """
        )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliverable_versions_org_id'), table_name='deliverable_versions')
    op.drop_index(op.f('ix_deliverable_versions_deliverable_id'), table_name='deliverable_versions')
    op.drop_table('deliverable_versions')
    op.drop_index(op.f('ix_deliverables_project_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_org_id'), table_name='deliverables')
    op.drop_table('deliverables')
    # ### end Alembic commands ###
