"""m5 feedback

Revision ID: bb9ef6da7470
Revises: 8d97db86db8a
Create Date: 2026-07-04 23:58:01.786927

"""
from alembic import op
import sqlalchemy as sa


revision = 'bb9ef6da7470'
down_revision = '8d97db86db8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.Enum('deliverable_version', 'entity', 'opportunity', name='feedback_subject'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_org_id'), 'feedback', ['org_id'], unique=False)
    op.create_index(op.f('ix_feedback_subject_id'), 'feedback', ['subject_id'], unique=False)
    # ### end Alembic commands ###

    # Row-Level Security, same shape as prior migrations (docs/05 §2).
    op.execute("ALTER TABLE feedback ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE feedback FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY feedback_tenant_isolation ON feedback
        USING (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
        WITH CHECK (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
        """
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_subject_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_org_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
