"""m2 knowledge model

Revision ID: c7352867592a
Revises: 0033006bc6ff
Create Date: 2026-07-04 09:41:26.357975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c7352867592a'
down_revision = '0033006bc6ff'
branch_labels = None
depends_on = None

TENANT_TABLES = ["entities", "entity_relations", "evidence", "review_items", "entity_history"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('change_source', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_history_entity_id'), 'entity_history', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_history_org_id'), 'entity_history', ['org_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='confidence'), nullable=False),
    sa.Column('review_state', sa.Enum('ai_generated', 'confirmed', 'edited', 'rejected', name='review_state'), nullable=False),
    sa.Column('novel', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_canonical_name'), 'entities', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_entities_org_id'), 'entities', ['org_id'], unique=False)
    op.create_index(op.f('ix_entities_project_id'), 'entities', ['project_id'], unique=False)
    op.create_index('ix_entities_project_type', 'entities', ['project_id', 'type'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('low_confidence', 'merge_proposal', 'question', name='review_item_kind'), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='review_item_status'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_org_id'), 'review_items', ['org_id'], unique=False)
    op.create_index(op.f('ix_review_items_project_id'), 'review_items', ['project_id'], unique=False)
    op.create_table('entity_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('from_id', sa.UUID(), nullable=False),
    sa.Column('to_id', sa.UUID(), nullable=False),
    sa.Column('rel_type', sa.String(length=50), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='confidence'), nullable=False),
    sa.Column('review_state', sa.Enum('ai_generated', 'confirmed', 'edited', 'rejected', name='review_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relations_from_id'), 'entity_relations', ['from_id'], unique=False)
    op.create_index(op.f('ix_entity_relations_org_id'), 'entity_relations', ['org_id'], unique=False)
    op.create_index(op.f('ix_entity_relations_project_id'), 'entity_relations', ['project_id'], unique=False)
    op.create_index(op.f('ix_entity_relations_to_id'), 'entity_relations', ['to_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('claimable_type', sa.String(length=50), nullable=False),
    sa.Column('claimable_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['element_id'], ['document_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_claimable', 'evidence', ['claimable_type', 'claimable_id'], unique=False)
    op.create_index(op.f('ix_evidence_org_id'), 'evidence', ['org_id'], unique=False)
    # ### end Alembic commands ###

    # Row-Level Security, same shape as migrations 001/002 (docs/05 §2).
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
            WITH CHECK (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
            """
        )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_org_id'), table_name='evidence')
    op.drop_index('ix_evidence_claimable', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_entity_relations_to_id'), table_name='entity_relations')
    op.drop_index(op.f('ix_entity_relations_project_id'), table_name='entity_relations')
    op.drop_index(op.f('ix_entity_relations_org_id'), table_name='entity_relations')
    op.drop_index(op.f('ix_entity_relations_from_id'), table_name='entity_relations')
    op.drop_table('entity_relations')
    op.drop_index(op.f('ix_review_items_project_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_org_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index('ix_entities_project_type', table_name='entities')
    op.drop_index(op.f('ix_entities_project_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_org_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_canonical_name'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_entity_history_org_id'), table_name='entity_history')
    op.drop_index(op.f('ix_entity_history_entity_id'), table_name='entity_history')
    op.drop_table('entity_history')
    # ### end Alembic commands ###
