"""m3 opportunities roi roadmap

Revision ID: cbd4e3fd608e
Revises: c7352867592a
Create Date: 2026-07-04 10:39:05.512993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'cbd4e3fd608e'
down_revision = 'c7352867592a'
branch_labels = None
depends_on = None

TENANT_TABLES = ["opportunities", "roi_models", "roadmap_items"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=True),
    sa.Column('taxonomy_type', sa.Enum('system_integration', 'rpa', 'workflow_automation', 'document_ai', 'decision_engine', 'generative_ai', 'knowledge_search', 'process_redesign', 'elimination', name='opportunity_taxonomy'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('complexity_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('rubric_version', sa.String(length=20), nullable=False),
    # Reuses the enum type created by the M2 migration.
    sa.Column('review_state', postgresql.ENUM('ai_generated', 'confirmed', 'edited', 'rejected', name='review_state', create_type=False), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_org_id'), 'opportunities', ['org_id'], unique=False)
    op.create_index(op.f('ix_opportunities_project_id'), 'opportunities', ['project_id'], unique=False)
    op.create_table('roadmap_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('horizon', sa.Enum('days_30', 'days_90', 'days_180', 'days_365', name='roadmap_horizon'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('quick_win', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_items_org_id'), 'roadmap_items', ['org_id'], unique=False)
    op.create_index(op.f('ix_roadmap_items_project_id'), 'roadmap_items', ['project_id'], unique=False)
    op.create_table('roi_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roi_models_opportunity_id'), 'roi_models', ['opportunity_id'], unique=True)
    op.create_index(op.f('ix_roi_models_org_id'), 'roi_models', ['org_id'], unique=False)
    # ### end Alembic commands ###

    # Row-Level Security, same shape as prior migrations (docs/05 §2).
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
            WITH CHECK (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
            """
        )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roi_models_org_id'), table_name='roi_models')
    op.drop_index(op.f('ix_roi_models_opportunity_id'), table_name='roi_models')
    op.drop_table('roi_models')
    op.drop_index(op.f('ix_roadmap_items_project_id'), table_name='roadmap_items')
    op.drop_index(op.f('ix_roadmap_items_org_id'), table_name='roadmap_items')
    op.drop_table('roadmap_items')
    op.drop_index(op.f('ix_opportunities_project_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_org_id'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
